POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NTU2NDE1MzksInVzZXJJZCI6MX0.5obj0_pnkYkWTYSEWKqyVIJ9iaGr5wXZB8E2PM54n5g

{
    "name" : "Test event",
    "description" : "Test event!!!",
    "location" : "A test location",
    "dateTime" : "2025-01-01T15:30:00.000Z"
}